name: Terraform CI/CD with Terratest

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Install Terratest
      run: go get -u github.com/gruntwork-io/terratest/modules/terraform

    - name: Run Terratest
      run: |
        go test -v ./test/terratest/
